name: polartoolkit_binder
channels:
  - conda-forge
dependencies:
  - python=3.11
  # runtime
  - polartoolkit=0.4
  - geopandas<1.0
  # interactive
  - geoviews
  - cartopy
  - ipyleaflet
  - ipython
  - ipykernel
  # viz
  - seaborn
  # - pip
  # pip:
  #   -U --pre --extra-index-url https://test.pypi.org/simple/ pygmt

